### ISSUE TITLE
Incomplete use of $count

### ISSUE THREAD

**Issue by consulthys** [kanthoney/odata-client#14]
According to [section 11.2.10](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_RequestingtheNumberofItemsinaCollect) of the current OData v4.01 specification, the `/$count` path can be used to retrieve the number of items of a collection of entities or items of a collection-valued property.

However, according to [section 11.2.6.5](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_SystemQueryOptioncount), it should also be possible to use `$count=true` as a system query option (i.e. query string parameter) in order to return the total count of items within a collection matching the request.

So, the following commit https://github.com/kanthoney/odata-client/commit/4900381d854d5a7560efd1ead9619944b7ce3b3f should be revised in order to include both `$count`.

One way to circumvent the problem right now is to call `custom()` as follows in order to support the second use above:

    q.custom({"$count":"true"})

=> will return `@odata.count` in the response

**Comment by kanthoney** [comment]
The latest commit allows use of count as a parameter by passing `true` to the function, eg

```
odata = new Odata({service: 'https://odata.example.com', resources: 'Customers'});
odata.count(true).query() // https://odata.example.com/Customers?%24count=true
```

**Comment by consulthys** [comment]
Fantastic!! Thanks for the quick response, much appreciated!

**Comment by kanthoney** [comment]
I've just published this now. Thanks for the suggestion by the way!

**Comment by consulthys** [comment]
Thanks much!
