### ISSUE TITLE
Need example of function call

### ISSUE THREAD

**Issue by roelvandun** [kanthoney/odata-client#24]
Is it besides querying a resource also possible to execute a OData function?

**Comment by kanthoney** [comment]
There's an example in the readme:

```
odata({service: 'https://example.com'}).fn('Customer', { Account: 'ACME01' }); // https://example.com/Customer(Account='ACME01')
```

**Comment by roelvandun** [comment]
Ah, thanks for letting me know.
The reason I didn't find it myself is because I think it's a bit hidden amongst the "narrowing operators" like `filter()`, `select()`, `count()` etc. 
I was in the understanding that you'd always need a resource|function, and the rest of the operators are optional. So for clarity it might better to separate `resource()` and `fn()` from the other functions?
Or maybe I'm just not understanding OData very well yet.

**Comment by kanthoney** [comment]
OK, thanks. I've moved the `resource` and `fn` methods to the top of that section to make them easier to find.
