### ISSUE TITLE
combining filters

### ISSUE THREAD

**Issue by roelvandun** [kanthoney/odata-client#25]
I need to combine filters to filter the data. E.g.:
```
?$filter=(key1 eq 'abc' and key2 eq '123') or (key1 eq 'def' and key2 eq '456')
```

when I try to do this with 
```
q.or('key1', '=', 'abc').and('key2', '=', '123')
 .or('key1', '=', 'def').and('key2', '=', '456')
```
that results in 
`(((key1 eq 'abc') and (key2 eq '123')) or (key1 eq 'def')) and (key2 eq '456')`, so the parenthesis are not as I need them to be.
Is there a way I can influence the grouping of filters?

**Comment by roelvandun** [comment]
Thanks for your reply, Kevin. I've simplified my question too much, so here is my second attempt.

those `(or().and())` blocks need to be added for each item in a list dynamically.
E.g.
```
items.forEach(item => {
   q.or('key1', '=', 'abc').and('key2', '=', '123')
}
```

**Comment by kanthoney** [comment]
Alternatively, you can now do

```
q.or([{ key1: 'abc', key2: '123' }, { key1: 'def', key2: '456' }])
// (key1 eq 'abc' and key2 eq '123') or (key1 eq 'def' and key2 eq '456')
```

**Comment by roelvandun** [comment]
This is working like a charm! Thanks so much for the swift support ❤️

**Comment by kanthoney** [comment]
Thanks for that! I've published this update to npm so you can go back to using the standard package.
