### ISSUE TITLE
improvement: return json body instead of string

### ISSUE THREAD

**Issue by roelvandun** [kanthoney/odata-client#26]
When doing a `Odata({format: 'json').get(...)`, it would be nice if the `result.body` would be a JSON object instead of a string that I have to manually parse to a JSON object.

**Comment by kanthoney** [comment]
Unfortunately I can't really change that without breaking it for everyone else who's using the package. I haven't tried it but

```
.get({ responseType: 'json' })
```

might work.

**Comment by roelvandun** [comment]
Awesome!
