### ISSUE TITLE
Need to send value as non-string

### ISSUE THREAD

**Issue by roelvandun** [kanthoney/odata-client#28]
In OData, a date is used without quotes. E.g. `~/Customers?$filter=Birthday eq 2015-12-14` or `~/SomeFunction(referenceDate eq 2023-02-15)`.

The library doesn't support sending dates without quotes. 
```OData().fn('SomeFunction', {referenceDate: '2023-02-15'})``` would result in `~/SomeFunction(referenceDate eq '2023-02-05')`.
Would it be possible to send those dates without quotes?

**Comment by kanthoney** [comment]
Try using Odata.exact:

```
Odata({ service: 'https://www.example.com' }).resource('service-name').fn('TheMethod', { param1: '123\
4', theDate: Odata.exact('2023-04-04') });
```

**Comment by roelvandun** [comment]
Thanks yet again!
