### ISSUE TITLE
can't filter by guid

### ISSUE THREAD

**Issue by mic1983** [kanthoney/odata-client#8]
when i try filter like Id eq guid'6e7a763b-0a7b-46a1-89d7-72cafa24cef2' i receive error
.filter("Id eq guid'6e7a763b-0a7b-46a1-89d7-72cafa24cef2'")
Please help

**Comment by kanthoney** [comment]
I think you need to leave off quotes for guids. Try this:

```
const odata = require('odata-client');
const uuid = require('uuid');

let q = odata({ service: 'https://example.com' })
    .filter('id', odata.exact(uuid.v4()));
console.log(q.query());
```

Which gives:

`https://example.com/?%24filter=id%20eq%20531f6a7f-7e99-44f6-809e-73fd62e4d5bf
`

**Comment by kanthoney** [comment]
Or use the brand new `type` feature:

```
q.filter('id', odata.type('guid', '531f6a7f-7e99-44f6-809e-73fd62e4d5bf')) // $filter=id eq guid'531f6a7f-7e99-44f6-809e-73fd62e4d5bf'
```

**Comment by mic1983** [comment]
Thanks!
